### ISSUE TITLE
JWL media window on the main screen

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/SbJwlLauncher#1]
First, thanks Antony for this useful app as Window size can be now sorted. And considering that JWL priority is changed to above normal, that's a bonus.

I noticed that if I accidentally launch again SbJwlLauncher.exe (once JWL is open), JWL media window moves from the 2nd screen to the main one. This happens every time, with or without using JwlMediaWin.
Is this the normal behavior or can be fixed?

**Comment by AntonyCorbett** [comment]
@LvDaniel Thanks - I'll investigate

**Comment by LvDaniel** [comment]
@AntonyCorbett Thanks, JWL Media Window doesn't brakes anymore on re-launch. 
If JWL is minimize in the taskbar, is it possible at SbJwlLauncher re-launch JWL to be restored? This is the way that JWL default shortcut works. If needed, I can open a new request.
Thanks again!

**Comment by AntonyCorbett** [comment]
@LvDaniel yes, a new issue would be best please. Thanks.
