### ISSUE TITLE
JWL white bar on top

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/SbJwlLauncher#2]
I don't know if this is an app issue or a problem with my PC (I haven't tested SbJwlLauncher on the KH's PC yet).
Sometimes after I close JWL and try to launch it again with SbJwlLauncher, I get a white bar at the top of JWL main window. This is not a problem, but if I minimize JWL main window when I restore it, will be restored maximized not with the size and position I've specified in the SbJwlLauncher. 
Somehow the window looks to be maximized when I launch JWL cause the maximize option is grayed out. I notice that this happens when I set the window to be larger than 1040 pixels in height (normally I use SbJwlLauncher.exe 0 0 1395 1047).
I don't know if it's related to this but my home PC 2nd screen doesn't have full HD resolution but 1024 x 768.

![image](https://user-images.githubusercontent.com/45002147/71784264-3c680180-2ffa-11ea-8352-ff4f816d69f8.png)

**Comment by LvDaniel** [comment]
I tested this on KH's PC where all the displays have the same resolution (1920 x 1080) and the result is the same.  If the height is 1040 or more the white bar appears when JWL is reopened.

**Comment by AntonyCorbett** [comment]
@LvDaniel The exact sequence is unclear. Please would you provide steps to reproduce? Thanks, Antony.

**Comment by LvDaniel** [comment]
@AntonyCorbett I've created a shortcut on desktop with the following target: "C:\Program Files (x86)\SbJwlLauncher\SbJwlLauncher.exe" 0 0 1403 1047
When I launch it for the first time everything is ok, JWL is opening as expected.
After I close JWL and re-launch it for several times the white bar appears and window looks to be maximized (as the option is grayed out) even if the size is respected. If I minimize JWL main window, on restore will be maximized across all the primary screen.
Once I get the white bar, if I close and re-launch JWL the bar won't disappear. I can get rid of it if I restore the JWL window (considering that is maximized) close it and re-launch JWL.
If any info is needed or I haven't been so clear please let me know and I'll try to give more details. Thank you

![image](https://user-images.githubusercontent.com/45002147/72079421-940cb280-3303-11ea-9c24-69235ed61280.png)

**Comment by LvDaniel** [comment]
I've tested this (closing JWL and reopening it for several times) thinking that sometimes JWL crashes and needs to be re-launched.
I've tried to simulate a crash, killing JWL from task manager. In this case at reopen JWL window shows normal without the white bar. Just when it's properly closes and reopen appears.

**Comment by AntonyCorbett** [comment]
@LvDaniel I can see how this happens. JWL remembers if it has been in the maximised state when last closed down. If so it attempts to maximize again at next launch which is not compatible with SbJwlLanucher which attempts to control its size.

**Comment by LvDaniel** [comment]
@AntonyCorbett Works perfect with the new release. Thank you!
